### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by muganwas** [ndoublehwp/woocommerce-simple-buy-now#2]
when you click the buy now button it goes to the single item page instead of the checkout page.

**Comment by andyhoanghuu** [comment]
Hi @muganwas,
Please tell me what is your payment method? And maybe give me a screenshot.

**Comment by muganwas** [comment]
I have paypal and cod.

Sent from Mail for Windows 10

**Comment by andyhoanghuu** [comment]
Hi @muganwas,
You can download and install the latest version [here](https://github.com/ndoublehwp/woocommerce-simple-buy-now/tree/1.0.4) then response me.
Make sure that the WooCommerce settings are perfect! [images](http://ndoublehwp.com/wp-content/uploads/2018/03/woo.png)
Thanks.
