### ISSUE TITLE
Redirect  

### ISSUE THREAD

**Issue by chhonhourseng** [ndoublehwp/woocommerce-simple-buy-now#3]
I want when i click but now, it Redirect  to checkout page

**Comment by andyhoanghuu** [comment]
Thanks for your request. I will review and release the next version. Maybe 1 or 2 days later.

**Comment by andyhoanghuu** [comment]
Hi there,
WooCommerce Simple Buy Now v1.0.5 is released. You can check the new feature now.
Thanks.
